name: Publish pypi package
run-name: test oidc
on: [push]
jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v5
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        run: env