name: Publish pypi package
run-name: test oidc
on: [push]
jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Publish release distributions to PyPI
        run: env